name: DApp Unit Testing

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  dapp_test:
    name: "Javascript/Typescript Unit testing"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.1
          cache: 'npm'
      - name: Upgrade NPM
        run: npm install -g npm
      - name: Install packages
        run: npm ci
        working-directory: app
      - name: === Unit-testing ===
        run: yarn react-app:test
        working-directory: app
